# Generated by Django 5.0.1 on 2024-01-07 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("bg-yellow-500", "bg-yellow-500"),
                            ("bg-pink-500", "bg-pink-500"),
                            ("bg-orange-500", "bg-orange-500"),
                            ("bg-blue-500", "bg-blue-500"),
                            ("bg-green-500", "bg-green-500"),
                            ("bg-red-500", "bg-red-500"),
                            ("bg-purple-500", "bg-purple-500"),
                        ],
                        default="bg-yellow-500",
                        max_length=50,
                    ),
                ),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="BlogItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_page.blogcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Blog Posts",
            },
        ),
    ]
