# Generated by Django 5.0.1 on 2024-01-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_page", "0002_alter_blogitems_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogitems",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
