# Generated by Django 5.0.1 on 2024-01-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_page", "0003_alter_blogitems_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogitems",
            old_name="image",
            new_name="images",
        ),
    ]
