# Generated by Django 5.0.1 on 2024-01-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_page", "0004_rename_image_blogitems_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogitems",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="item_images"),
        ),
    ]
