# Generated by Django 5.0.1 on 2024-01-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_page", "0005_alter_blogitems_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name_plural": "BackCategory",
            },
        ),
        migrations.AddField(
            model_name="blogitems",
            name="back_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core_page.backcategory",
            ),
        ),
    ]
