# Generated by Django 5.0.1 on 2024-01-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_page", "0007_subscriber"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriber",
            options={"verbose_name_plural": "Subscribers"},
        ),
    ]
